- name: Create virtual network - "{{item.name}}"
  azure_rm_virtualnetwork:
    resource_group: "{{vars.rg}}"
    name: "{{item.name}}"
    address_prefixes: "{{item.add_pref}}"
  loop: "{{vnets}}"
  register: vnets
  
- debug:
    msg: "VNets creation output: {{vnets}}"
