- name: Check who i am...
  win_command: whoami

- name: Check where i am...
  win_command: cmd.exe /k chdir
  register: pwd

- name: Copy file with owner and permissions
  copy:
    src: windows-packages.json
    dest: "{{pwd}}\\windows-updates.json"
    #owner: leonardopuga

- name: Getting Updates list...
  win_command: "type {{pwd}}\\windows-updates.json"
  register: result

##- name: Save Updates data to var...
##  set_fact:
##    updates: "{{ result.stdout | from_json | json_query(jmesquery) }}"
##  vars:
##    jmesquery: "updates[*]"
##- debug: 
##    msg: "Updates from list: {{updates}}"
##    #- name: Getting updates list...
##    #set_fact:
##    #updates: "{{ data | from_json }}"
##    #vars:
##    #jmesquery: '*.data.updates[*]'
##
##- name: Manage Updates VM - "{{vars.vm_name}}"
##  become: yes
##  become_user: root
##  #become_method: sudo
##  ansible.windows.win_updates:
##    category_names:
##      - "{{item.name}}"
##      state: "{{item.state}}"
##  loop: "{{updates}}"
##  #when: vars.vm_stop
##  register: pkgs
##- debug:
##    msg: "Updates management: {{pkgs}}"
##  #when: vars.vm_stop
##
##- name: Install all security, critical, and rollup updates without a scheduled task
##  ansible.windows.win_updates:
##    category_names:
##      - SecurityUpdates
##      - CriticalUpdates
##      - UpdateRollups
