- name: Create Azure Resources
  hosts: localhost
  connection: local
  vars:
    rg: rg-auto-ansible
    vnetname: vnet-auto-ansible
    subnetname: subnet-auto-ansible
  roles:
    - azrm-rg
    - azrm-vnet
    - azrm-subnet
