- name: Create VMs - "{{vars.vm_name}}"
  azure_rm_virtualmachine:
    resource_group: "{{item.resource_group}}"
    name: "{{item.name}}"
    vm_size: "{{item.vm_size}}"
    admin_username: "{{item.admin_username}}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{item.admin_username}}/.ssh/authorized_keys"
        key_data: "{{item.key_data}}"
    network_interfaces: "{{item.network_interfaces}}"
    image:
      offer: "{{item.offer}}"
      publisher: "{{item.publisher}}"
      sku: "{{item.sku}}"
      version: "{{item.version}}"
  loop: "{{vms}}"
  when: vars.vm_create
  register: vms
- debug:
    msg: "VMs creation output: {{vms}}"
  when: vars.vm_create
