- name: Copy file with owner and permissions
  copy:
    src: redhat-packages.json
    dest: redhat-packages.json
    owner: leonardopuga

- name: Getting packages list...
  shell: cat "{{vars.jsonpath}}"
  register: result

- name: Save packages data to var...
  set_fact:
    packages: "{{ result.stdout | from_json | json_query(jmesquery) }}"
  vars:
    jmesquery: "packages[*]"
- debug: 
    msg: "packages from list: {{packages}}"
    #- name: Getting packages list...
    #set_fact:
    #packages: "{{ data | from_json }}"
    #vars:
    #jmesquery: '*.data.packages[*]'

- name: Manage packages VM - "{{vars.vm_name}}"
  become: yes
  become_user: root
  #become_method: sudo
  yum:
    name: "{{item.name}}"
    state: "{{item.state}}"
  loop: "{{packages}}"
  #when: vars.vm_stop
  register: pkgs
- debug:
    msg: "Packages management: {{pkgs}}"
  #when: vars.vm_stop
