- name: Creating resource group - "{{ name }}"
  azure_rm_resourcegroup:
    name: "{{ item.name }}"
    location: "{{ item.location }}"
  register: rg_output
  loop: "{{ rgs }}"
- debug:
    var: rg_output
