- name: Creating resource group - "{{ name }}"
  azure_rm_resourcegroup:
    name: "{{ item.name }}"
    location: "{{ item.region }}"
  register: rg_output
  loop: "{{ rgs }}"
- debug:
    msg: "Resource Group creation output: {{rg_output}}"
