- name: Create Sub network
  azure_rm_subnet:
    resource_group: "{{vars.rg}}"
    name: "{{item.name}}"
    address_prefix: "{{item.add_pref}}"
    virtual_network: "{{item.vnet}}"
  loop: "{{subnets}}"
  register: subnets
  
- debug:
    msg: "SubNets creation output: {{subnets}}"
